version: "3.9"

services:
  rag-business-chatbot:
    image: rag-business-chatbot:latest
    container_name: rag_business_chatbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./vector_db:/app/vector_db
      - ./businesses:/app/businesses
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
